spring.datasource.url=jdbc:postgresql://localhost:5432/tictactoe
spring.datasource.username=yuta
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#JWT
jwt.access-secret=${JWT_ACCESS_SECRET:dev-only-access-secret-which-is-at-least-32-bytes-long}
jwt.refresh-secret=${JWT_REFRESH_SECRET:dev-only-refresh-secret-which-is-at-least-32-bytes-long}
jwt.access-expiration-ms=1800000
jwt.refresh-expiration-ms=2592000000